name: Go

on:
  push:
    branches: [ "master", "lg-update" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    name: lint
    strategy:
      matrix:
        go: [1.16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.2
  test:
    strategy:
      matrix:
        go: [1.16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        cache: false
    - name: Run Tests
      run: make test